### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by veso266** [Tampa/DirectoryLister#1]
Hi there
I wanted to make a pull request but whenever I want to make it it automaticly makes it into mijorepusic/DirectoryLister

instead of Tampa/DirectoryLister??
anyhow here are my chaneges merged into yours: https://github.com/veso266/DirectoryLister/tree/Tempa/master

and fixed a bug where a .desc file wasn't shown if url didn't have = in it: https://github.com/veso266/DirectoryLister/commit/79e33902dde2bcc79b04b2f4407cc43e9e593c6e

if you are able to merge this into your branch go ahead :smile:

**Comment by Tampa** [comment]
You need to change the remote part of the repo when you locally clone.

Anyways, I merged your changes and fixed a few more things. I will be sticking to the bootstrap theme for now, I also removed a few of the osx things you stuffed in, to ease the look into the respective systems rather than forcing a change.

There are still a bunch of errors in the console regarding both css and the js for fetching the descriptions, I plan to fix those next and then create another release.

**Comment by veso266** [comment]
great
I see you customized dark version a bit :smile:

**Comment by Tampa** [comment]
I merged your download.php directly into the main index.php, less files. Also moved the js out of the theme, it really should not be in there. I am updating readme and default setup as well so it is more clear what can be done, planning a 2.9.0 release soon. After that for 3.0.0 some rewriting perhaps, clean some code, work on fixing some errors.

**Comment by veso266** [comment]
:smile: 

why can't js files be in the theme, I think original author intended a theme to be more like a plugin then a style addon

as if original Directory lister upates you can just merge DirectoryLister.php and leave the rest intact everything will still work (won't have the new features but will work)

that is also why I left ?hash part also show downloads because I wanted to make everything but my theme (lets call it plugin) as intacts as possible

BTW: I see you load the js file from the theme anyway so you should move it back as people would get confused (they would take the theme and be like: "why doesn't it work? Oh I forgot the js file :smile: " )

BTW: How can update my branch with the changes you made here and leave my commit history intact?

**Comment by Tampa** [comment]
The js in there has basically nothing to do with the theme itself, apart from maybe the dark/light switch, the rest is stuff to make the modals and descriptions work, just seems nicer to do it this way and have themes load their specific js after the fact.

The current head should have most of your features working, you can test here: http://two66.com/DirectoryLister/

You can checkout to a branch rather than into your master to keep your changes intact :)

**Comment by veso266** [comment]
yea I wanted to checkout into here: https://github.com/veso266/DirectoryLister/tree/Tempa/master
anyway just don't know what command I have to type :smile: 

nice demo you put up here :smile: maybe add downloads.two66.com and put some real files there so people can use your download site, then come here and use your fork :smile:

**Comment by Tampa** [comment]
I use Git Extensions as I code on Windows, it has buttons for that :D 

I do already use it on other sites, hence why I picked up developing it further to fit my needs. I just put that one up as direct testing grounds for fiddling with themes.

**Comment by veso266** [comment]
am what buttons?
![GitEx](https://user-images.githubusercontent.com/6347325/60337295-fa069d80-99a2-11e9-912f-1fb4a7251dc8.png)

I use 
![Github](https://user-images.githubusercontent.com/6347325/60337350-1d314d00-99a3-11e9-9767-db4bc5064d92.PNG)

not sure where I found it but I like it :smile:
